#!/bin/bash

source_dirs="lib bin manage/sql"
args=${*:-"bin/main.exe"}
#	cmd="dune exec ${args}"
cmd="dune exec --display=quiet ${args}"

function sigint_handler() {
    kill "$(jobs -pr)"
    reset # restore console output
    exit 1
}

trap sigint_handler SIGINT

while true; do
    ./manage/dev/init_db # Move one-up if I want to keep db state accross reloads
    clear
    dune build
    $cmd &
    fswatch -r -1 --monitor poll_monitor $source_dirs
    printf "\nRestarting main.exe due to filesystem change\n"
    kill "$(jobs -pr)"
done
